FROM python:3.10.10

RUN mkdir /opt/app
WORKDIR /opt/app

COPY ./app .

RUN apt update
# RUN apt upgrade -y
RUN apt install libmariadb3 libmariadb-dev

RUN pip install --upgrade pip
RUN pip3 install mariadb

CMD ["python3", "./connection.py"]

# docker build -t linuxapp_tienda:0.4 -f ./Dockerfile_linuxapp .
# docker run -d --name linuxapp_tienda linuxapp_tienda:0.4
