FROM python:bullseye

RUN mkdir /opt/app
WORKDIR /opt/app

COPY ./app .

RUN apt update
RUN apt upgrade -y

RUN wget -c http://ftp.us.debian.org/debian/pool/main/l/leptonlib/leptonica-progs_1.79.0-1.1+deb11u1_amd64.deb

RUN apt update
RUN apt upgrade -y

RUN apt install -yq libc6 
RUN apt install -yq ./leptonica-progs_1.79.0-1.1+deb11u1_amd64.deb

RUN apt install -yq libmariadb3 libmariadb-dev
RUN apt install -yq python3 pip


RUN pip install --upgrade pip
RUN pip3 install mariadb==1.0.0

# CMD ["python3", "./connection.py"]

# docker build -t linuxapp_tienda:0.7 -f ./Dockerfile_linuxapp .
# docker run -d --name linuxapp_tienda linuxapp_tienda:0.7





# FROM debian:bookworm-20230227

# RUN mkdir /opt/app
# WORKDIR /opt/app

# COPY ./app .

# RUN apt update
# # # RUN apt upgrade -y

# # RUN wget -c http://ftp.us.debian.org/debian/pool/main/l/leptonlib/libleptonica-dev_1.82.0-3+b2_amd64.deb
# # RUN apt install ./libleptonica-dev_1.82.0-3+b2_amd64.deb

# RUN apt install -yq libmariadb3 libmariadb-dev
# RUN apt install -yq python3 pip

# # # RUN pip install --upgrade pip
# RUN pip3 install mariadb

# # CMD ["python3", "./connection.py"]
